<a href="https://colab.research.google.com/github/ibrahim10sy/learn-python/blob/main/Filtrage_conditionnelle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/tips.csv')

In [5]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,49.59,5.76,Female,No,Sat,Lunch,1,49.59,Michael Avila,1900150430370796,Sat9766
1,44.84,1.36,Female,Yes,Thur,Dinner,2,22.42,Tonya Carter,9662633192418041,Thur8155
2,44.09,4.15,Male,No,Thur,Lunch,5,8.82,Keith Wong,8931077392011890,Thur3955
3,43.73,8.10,Female,No,Fri,Dinner,1,43.73,Nathaniel Harris,7537214471119914,Fri9117
4,14.64,5.38,Male,No,Sat,Lunch,6,2.44,Tonya Carter,6707651664586514,Sat9462

In [8]:
# filtrage
bool_series = df['total_bill']>40

In [9]:
df[bool_series]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,49.59,5.76,Female,No,Sat,Lunch,1,49.59,Michael Avila,1900150430370796,Sat9766
1,44.84,1.36,Female,Yes,Thur,Dinner,2,22.42,Tonya Carter,9662633192418041,Thur8155
2,44.09,4.15,Male,No,Thur,Lunch,5,8.82,Keith Wong,8931077392011890,Thur3955
3,43.73,8.10,Female,No,Fri,Dinner,1,43.73,Nathaniel Harris,7537214471119914,Fri9117
5,48.15,6.74,Male,No,Fri,Dinner,6,8.03,Travis Walters,5384340499728358,Fri4944
...,...,...,...,...,...,...,...,...,...,...,...
223,48.03,8.50,Female,Yes,Thur,Lunch,5,9.61,Monica Sanders,5905637357586994,Thur6738
235,42.77,8.99,Male,No,Thur,Lunch,2,21.39,Travis Walters,124668007388340,Thur5465
237,42.80,2.39,Female,Yes,Thur,Dinner,5,8.56,Nathaniel Harris,8471930982220635,Thur5988
239,48.48,3.59,Male,No,Fri,Lunch,3,16.16,Tonya Carter,420616308530044,Fri2931
240,47.14,8.75,Female,Yes,Sun,Lunch,6,7.86,Douglas Tucker,5592533605186633,Sun1746

In [11]:
# par sexe
df[df['sex'] == 'Male']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
2,44.09,4.15,Male,No,Thur,Lunch,5,8.82,Keith Wong,8931077392011890,Thur3955
4,14.64,5.38,Male,No,Sat,Lunch,6,2.44,Tonya Carter,6707651664586514,Sat9462
5,48.15,6.74,Male,No,Fri,Dinner,6,8.03,Travis Walters,5384340499728358,Fri4944
6,11.40,7.92,Male,No,Fri,Lunch,6,1.90,Travis Walters,5564466922876620,Fri3642
9,37.97,1.42,Male,Yes,Fri,Dinner,5,7.59,Michael Avila,6824370763844661,Fri1436
...,...,...,...,...,...,...,...,...,...,...,...
234,24.27,9.96,Male,Yes,Sat,Dinner,5,4.85,Michelle Hardin,4689196998932232,Sat6447
235,42.77,8.99,Male,No,Thur,Lunch,2,21.39,Travis Walters,124668007388340,Thur5465
236,25.91,2.76,Male,No,Fri,Lunch,2,12.96,Douglas Tucker,8720235499119583,Fri4221
239,48.48,3.59,Male,No,Fri,Lunch,3,16.16,Tonya Carter,420616308530044,Fri2931
243,22.50,3.84,Male,No,Fri,Lunch,1,22.50,Travis Walters,5399041384021608,Fri9944

In [16]:
# par nom
df[df['Payer Name'] == 'Keith Wong']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
2,44.09,4.15,Male,No,Thur,Lunch,5,8.82,Keith Wong,8931077392011890,Thur3955
16,25.72,9.39,Male,No,Sat,Dinner,5,5.14,Keith Wong,8599749080023370,Sat7521
26,38.03,8.10,Male,Yes,Thur,Dinner,1,38.03,Keith Wong,5329426704144900,Thur4859
33,46.97,1.95,Male,Yes,Sat,Lunch,3,15.66,Keith Wong,2563395421143868,Sat4006
39,48.00,5.66,Male,Yes,Sat,Dinner,5,9.60,Keith Wong,8850441856042909,Sat6480
54,29.04,7.00,Male,Yes,Sun,Lunch,6,4.84,Keith Wong,9976658948977693,Sun7493
59,34.96,9.17,Female,Yes,Sun,Dinner,1,34.96,Keith Wong,8063606077548697,Sun2729
63,25.00,9.34,Male,Yes,Fri,Dinner,6,4.17,Keith Wong,2658981361876295,Fri2256
82,36.63,9.18,Male,Yes,Sun,Lunch,4,9.16,Keith Wong,2568721071215295,Sun9180
101,49.07,4.94,Female,No,Fri,Lunch,3,16.36,Keith Wong,1621585235096924,Fri5894
111,11.00,6.68,Female,No,Sun,Lunch,2,5.50,Keith Wong,1677056073271340,Sun6725
113,26.25,2.34,Male,No,Sat,Dinner,4,6.56,Keith Wong,455318769262846,Sat9059
115,46.34,2.00,Female,Yes,Fri,Dinner,3,15.45,Keith Wong,5611716146268012,Fri6467
121,38.73,7.65,Male,Yes,Sun,Dinner,2,19.36,Keith Wong,2282707257305632,Sun1663
139,46.71,5.29,Female,Yes,Fri,Lunch,2,23.36,Keith Wong,5602893985428238,Fri1009
160,19.85,7.88,Female,No,Fri,Lunch,1,19.85,Keith Wong,8752324639807108,Fri1747
163,31.68,1.00,Male,No,Sun,Lunch,5,6.34,Keith Wong,2903479242040270,Sun7274
177,11.08,1.69,Female,No,Thur,Lunch,3,3.69,Keith Wong,3416448079065227,Thur6086
194,13.01,1.07,Male,Yes,Sun,Dinner,5,2.60,Keith Wong,6200023131973418,Sun9969
210,19.83,8.49,Male,No,Sun,Lunch,3,6.61,Keith Wong,3870690365595410,Sun9080
221,34.85,2.33,Male,No,Sat,Lunch,3,11.62,Keith Wong,5296620151144497,Sat4858
227,38.07,1.33,Male,Yes,Thur,Dinner,1,38.07,Keith Wong,4978882836757632,Thur6047
242,18.12,8.12,Female,No,Sun,Lunch,3,6.04,Keith Wong,949194541098695,Sun2552

In [22]:
# condition multiple
c1 = df['total_bill'] > 30
c2 = df['tip'] >= 5
c3 = df['sex'] == 'Male'
c4 = df['smoker'] == 'Yes'
df[c2 & c1 & c3 & c4]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
21,36.02,6.05,Male,Yes,Thur,Lunch,3,12.01,Michael Avila,7499860308523082,Thur3984
26,38.03,8.10,Male,Yes,Thur,Dinner,1,38.03,Keith Wong,5329426704144900,Thur4859
37,48.26,6.68,Male,Yes,Thur,Lunch,4,12.06,Michael Avila,9129226422363525,Thur7852
39,48.00,5.66,Male,Yes,Sat,Dinner,5,9.60,Keith Wong,8850441856042909,Sat6480
58,40.55,6.67,Male,Yes,Sat,Dinner,6,6.76,Michelle Hardin,7616234029038220,Sat3949
82,36.63,9.18,Male,Yes,Sun,Lunch,4,9.16,Keith Wong,2568721071215295,Sun9180
110,35.80,8.56,Male,Yes,Fri,Dinner,5,7.16,Douglas Tucker,6519136955630471,Fri3347
121,38.73,7.65,Male,Yes,Sun,Dinner,2,19.36,Keith Wong,2282707257305632,Sun1663
165,48.24,8.43,Male,Yes,Sat,Lunch,3,16.08,Nathaniel Harris,6275430739880567,Sat7934
173,47.45,5.90,Male,Yes,Sun,Lunch,2,23.73,Monica Sanders,4981707457259681,Sun1192
186,47.11,7.32,Male,Yes,Thur,Dinner,1,47.11,Travis Walters,4458215595547921,Thur2494
200,39.93,7.92,Male,Yes,Thur,Lunch,5,7.99,Christy Cunningham,4689559738742894,Thur1719
203,32.72,6.15,Male,Yes,Sun,Dinner,5,6.54,Travis Walters,1728061949127606,Sun6146
208,40.70,8.39,Male,Yes,Sat,Dinner,6,6.78,Michael Avila,8728789812076677,Sat1257
215,47.50,8.49,Male,Yes,Thur,Lunch,4,11.88,Travis Walters,1210870123541359,Thur8350

In [28]:
options  = ['Lunch','Dinner']

In [29]:
df['time'].isin(options)

0      True
1      True
2      True
3      True
4      True
       ...
239    True
240    True
241    True
242    True
243    True
Name: time, Length: 244, dtype: bool