<a href="https://colab.research.google.com/github/ibrahim10sy/learn-python/blob/main/groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import random

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/tips.csv')

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,49.59,5.76,Female,No,Sat,Lunch,1,49.59,Michael Avila,1900150430370796,Sat9766
1,44.84,1.36,Female,Yes,Thur,Dinner,2,22.42,Tonya Carter,9662633192418041,Thur8155
2,44.09,4.15,Male,No,Thur,Lunch,5,8.82,Keith Wong,8931077392011890,Thur3955
3,43.73,8.10,Female,No,Fri,Dinner,1,43.73,Nathaniel Harris,7537214471119914,Fri9117
4,14.64,5.38,Male,No,Sat,Lunch,6,2.44,Tonya Carter,6707651664586514,Sat9462

In [ ]:
df.groupby(['total_bill','tip'])['Payer Name']

In [ ]:
df.groupby(['total_bill','tip']).mean()

TypeError: agg function failed [how->mean,dtype->object]